using FoodstoreApi.Core.Entities.Finance;
using FoodstoreApi.Usecase.DTOs.Finance;
using FoodstoreApi.Usecase.Interfaces;
namespace FoodstoreApi.Usecase.Services;
public sealed class FinanceOperationsService(IFinanceOperationsRepository repository, ITenantContext tenantContext) : IFinanceOperationsService
{
    public Task<IReadOnlyList<FinanceExceptionDto>> ExceptionsAsync(Guid organizationId, CancellationToken ct = default) => repository.ExceptionsAsync(organizationId, ct);
    public Task<IReadOnlyList<FinanceExceptionDto>> UnmatchedPaymentsAsync(CancellationToken ct = default) => repository.UnmatchedPaymentsAsync(ct);
    public Task<FinanceAdjustmentRequest?> GetAdjustmentAsync(Guid id, CancellationToken ct = default) => repository.AdjustmentAsync(id, ct);
    public async Task<FinanceAdjustmentRequest> RequestAdjustmentAsync(CreateAdjustmentRequest request, Guid actorId, CancellationToken ct = default) { if (request.Amount == 0 || string.IsNullOrWhiteSpace(request.ReasonCode) || string.IsNullOrWhiteSpace(request.Reason)) throw new InvalidOperationException("Amount, reason code and reason are required."); var item = new FinanceAdjustmentRequest { OrganizationId = request.OrganizationId, LedgerAccountId = request.LedgerAccountId, Amount = request.Amount, Currency = request.Currency, ReasonCode = request.ReasonCode, Reason = request.Reason, RequestedBy = actorId, CreatedBy = actorId }; await repository.AddAdjustmentAsync(item, ct); return item; }
    public async Task<FinanceAdjustmentRequest> ApproveAdjustmentAsync(Guid id, Guid actorId, CancellationToken ct = default) { var item = await repository.AdjustmentAsync(id, ct) ?? throw new InvalidOperationException("Adjustment request was not found."); if (item.Status != "pending" || item.RequestedBy == actorId) throw new InvalidOperationException("A different user must approve a pending adjustment."); item.Status = "approved"; item.ApprovedBy = actorId; item.ApprovedAt = DateTime.UtcNow; await repository.ApproveAdjustmentAsync(item, ct); return item; }
    public Task<IReadOnlyList<FinanceAdjustmentRequest>> AdjustmentsAsync(Guid organizationId, CancellationToken ct = default) => repository.AdjustmentsAsync(organizationId, ct);
    public async Task<ReconciliationCase> CreateCaseAsync(CreateReconciliationRequest request, Guid actorId, CancellationToken ct = default) { var item = new ReconciliationCase { OrganizationId = request.OrganizationId, BranchId = tenantContext.BranchId, SettlementBatchId = request.SettlementBatchId, SourceType = request.SourceType, SourceReference = request.SourceReference, InternalAmount = request.InternalAmount, ExternalAmount = request.ExternalAmount, Currency = request.Currency, EvidenceUrl = request.EvidenceUrl, CreatedBy = actorId }; await repository.AddCaseAsync(item, ct); return item; }
    public async Task<ReconciliationCase> ResolveCaseAsync(Guid id, ResolveReconciliationRequest request, Guid actorId, CancellationToken ct = default) { var item = await repository.CaseAsync(id, ct) ?? throw new InvalidOperationException("Reconciliation case was not found."); if (item.Status != "open") throw new InvalidOperationException("Only open reconciliation cases can be resolved."); item.Status = "resolved"; item.Resolution = request.Resolution; item.EvidenceUrl = request.EvidenceUrl ?? item.EvidenceUrl; item.ResolvedBy = actorId; item.ResolvedAt = DateTime.UtcNow; await repository.SaveCaseAsync(item, ct); return item; }
    public Task<IReadOnlyList<ReconciliationCase>> CasesAsync(Guid organizationId, CancellationToken ct = default) => repository.CasesAsync(organizationId, ct);
    public Task<ReconciliationCase?> GetCaseAsync(Guid id, CancellationToken ct = default) => repository.CaseAsync(id, ct);
}
